name: Receive request from another repository

on:
  workflow_dispatch:

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run some hello
        run: echo "Hello, world!"  

  create-kind:
   uses: lucasjct/reusable-workflows/.github/workflows/create-cluster.yml@main
